spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Capstone2020SCPA!
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true